services:
  - type: web
    name: progyan-backend
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_PATH
        value: ./data
      - key: PYTHON_VERSION
        value: "3.11.9"
    healthCheckPath: /api/v1/health
