services:
  - type: web
    name: progyan-backend
    env: python
    # Change the buildCommand to run your script
    buildCommand: "./build.sh" 
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_PATH
        value: ./data
    healthCheckPath: /api/v1/health
